version: "1.34"

lr: 1e-4
log_step: 1
split: 0
batch_size: 8
sr: 16000

datasets:
  - jamendo
  - emomusic
  # - pmemo
  # - deam


model:
  encoder: "MERT"
  layers:
    - 5
    - 6
  classifier: "linear-mt-attn-ck"
  kd: True
  # - linear
  # - linear-large
  # - linear-small
  # - linear-attn
  # - linear-attn-ck
  # - linear-mt
  # - linear-mt-v2
  # - linear-mt-small
  # - linear-mt-small-v2
  # - linear-mt-attn
  # - linear-mt-attn-ck
  
  lr: 1e-4

# audio_path: './dataset/jamendo'
# subset: 'moodtheme'

dataset:
  jamendo:
    root: './dataset/jamendo'
    subset: 'moodtheme'
    batch_size: 8
    output_size : 56
    split: 0
    segment_type: "all" # [all,f10s,f30s,10s,30s]
    num_workers: 4
  dmdd:
    root: './dataset/dmdd'
    batch_size: 8
    output_size : 2 
    segment_type: "all" # [all,f10s,f30s,10s,30s]
    num_workers: 4
  deam:
    root: './dataset/deam'
    batch_size: 8
    output_size : 2 
    segment_type: "all" # [all,f10s,f30s,10s,30s]
    num_workers: 4
  pmemo:
    root: './dataset/pmemo'
    batch_size: 8
    output_size : 2 
    segment_type: "all" # [all,f10s,f30s,10s,30s]
    num_workers: 4
  emomusic:
    root: './dataset/emomusic'
    batch_size: 8
    output_size : 2 
    segment_type: "all" # [all,f10s,f30s,10s,30s]
    num_workers: 4
  muse:
    root: './dataset/muse'
    batch_size: 8
    output_size : 3 # arounsal/valence/dominance 
    segment_type: "all" # [all,f10s,f30s,10s,30s]
    num_workers: 4
  soundtrack:
    root: './dataset/soundtrack'
    batch_size: 8
    output_size : 3
    segment_type: "all" # [all,f10s,f30s,10s,30s]
    num_workers: 4


# --------------------------------------- #
genre_class_size: 87
mood_class_size: 56
instr_class_size: 40
dac_latents_size: 72
dac_rvq_size: 9
# --------------------------------------- #
# model_save_path: './saved_models/'
# results_save_path: './results/'

# hydra:
#   job:
#     chdir: True
  # - MERT M2L LIBROSA Encodec DAC
  # aggr_method: "mean"
  # - mean
  # - median
  # - 80th_percentile
  # - max


#PMEMO BEST 0.5435 0.7723
checkpoint_pmemo: "tb_logs/train_audio_classification/version_453/checkpoints/33-0.0095.ckpt"

#DEAM BEST
checkpoint_deam: "tb_logs/train_audio_classification/version_455/checkpoints/33-0.6716.ckpt"

#EMOMUSIC BEST (0.5957 0.7489)
checkpoint_emomusic: "tb_logs/train_audio_classification/version_454/checkpoints/72-0.6225.ckpt"

#JAMENDO BEST (0.1469, 0.778)
checkpoint_jamendo: "tb_logs/train_audio_classification/version_456/checkpoints/last.ckpt"
